# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-10-30 06:15
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userinformation',
            old_name='name',
            new_name='first_name',
        ),
        migrations.RenameField(
            model_name='userinformation',
            old_name='date_of_birth',
            new_name='other_names',
        ),
        migrations.RenameField(
            model_name='userinformation',
            old_name='race',
            new_name='status',
        ),
    ]
