# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-10-30 06:16
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_auto_20181030_0915'),
    ]

    operations = [
        migrations.AddField(
            model_name='userinformation',
            name='profile_pic',
            field=models.ImageField(blank=True, null=True, upload_to='profile_pic/'),
        ),
    ]
