# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-10-30 06:16
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_userinformation_profile_pic'),
    ]

    operations = [
        migrations.AddField(
            model_name='userinformation',
            name='phone_number',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
