# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-10-30 06:19
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_userinformation_phone_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='userinformation',
            name='email',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
    ]
