# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-10-30 06:46
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_auto_20181030_0927'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userinformation',
            name='blood_group',
        ),
    ]
