# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-10-30 07:50
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_remove_userinformation_blood_group'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userinformation',
            old_name='last_name',
            new_name='Day',
        ),
    ]
