# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-10-30 08:00
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0010_auto_20181030_1053'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userinformation',
            name='last_name',
            field=models.CharField(max_length=150),
        ),
    ]
